package kohdeluettelo;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2015.07.29 17:49:38 // Generated by ComTest
 *
 */
public class KohdeluokkaTest {



  // Generated by ComTest BEGIN
  /** testAnna85 */
  @Test
  public void testAnna85() {    // Kohdeluokka: 85
    Kohdeluokka koh = new Kohdeluokka(); 
    koh.parse("   4   |  1  |   Planeetta  | "); 
    assertEquals("From: Kohdeluokka line: 88", "4", koh.anna(0)); 
    assertEquals("From: Kohdeluokka line: 89", "1", koh.anna(1)); 
    assertEquals("From: Kohdeluokka line: 90", "Planeetta", koh.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta114 */
  @Test
  public void testAseta114() {    // Kohdeluokka: 114
    Kohdeluokka koh = new Kohdeluokka(); 
    assertEquals("From: Kohdeluokka line: 116", null, koh.aseta(0,"1")); 
    assertEquals("From: Kohdeluokka line: 117", null, koh.aseta(1,"1")); 
    assertEquals("From: Kohdeluokka line: 118", null, koh.aseta(2,"Merkurius")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone159 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone159() throws CloneNotSupportedException {    // Kohdeluokka: 159
    Kohdeluokka koh = new Kohdeluokka(); 
    koh.parse("  10   |  9  |   Makemake   "); 
    Kohdeluokka kopio = koh.clone(); 
    assertEquals("From: Kohdeluokka line: 164", koh.toString(), kopio.toString()); 
    koh.parse("   1   |  11  |   Venus  "); 
    assertEquals("From: Kohdeluokka line: 166", false, kopio.toString().equals(koh.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi217 */
  @Test
  public void testRekisteroi217() {    // Kohdeluokka: 217
    Kohdeluokka planeetta1 = new Kohdeluokka(); 
    assertEquals("From: Kohdeluokka line: 219", 0, planeetta1.getKohdeNro()); 
    planeetta1.rekisteroi(); 
    Kohdeluokka planeetta2 = new Kohdeluokka(); 
    planeetta2.rekisteroi(); 
    int n1 = planeetta1.getKohdeNro(); 
    int n2 = planeetta2.getKohdeNro(); 
    assertEquals("From: Kohdeluokka line: 225", 0, n2-n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString263 */
  @Test
  public void testToString263() {    // Kohdeluokka: 263
    Kohdeluokka kohdeluokka = new Kohdeluokka(); 
    kohdeluokka.parse("   10   |  9  |   Makemake    "); 
    assertEquals("From: Kohdeluokka line: 266", "10|9|Makemake", kohdeluokka.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse287 */
  @Test
  public void testParse287() {    // Kohdeluokka: 287
    Kohdeluokka kohdeluokka = new Kohdeluokka(); 
    kohdeluokka.parse("   11   |  10  |   Pluto    "); 
    assertEquals("From: Kohdeluokka line: 290", 11, kohdeluokka.getKohdeluokanNro()); 
    assertEquals("From: Kohdeluokka line: 291", "11|10|Pluto", kohdeluokka.toString()); 
  } // Generated by ComTest END
}