package kohdeluettelo;
// Generated by ComTest BEGIN

import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2015.07.09 11:49:02 // Generated by ComTest
 *
 */
public class KohdeluokatTest {



  // Generated by ComTest BEGIN
  /** testIterator72 */
  @Test
  public void testIterator72() {    // Kohdeluokat: 72
    Kohdeluokat kohdeluokat = new Kohdeluokat(); 
    Kohdeluokka testi21 = new Kohdeluokka(2); kohdeluokat.lisaa(testi21); 
    Kohdeluokka testi11 = new Kohdeluokka(1); kohdeluokat.lisaa(testi11); 
    Kohdeluokka testi22 = new Kohdeluokka(2); kohdeluokat.lisaa(testi22); 
    Kohdeluokka testi12 = new Kohdeluokka(1); kohdeluokat.lisaa(testi12); 
    Kohdeluokka testi23 = new Kohdeluokka(2); kohdeluokat.lisaa(testi23); 
    Iterator<Kohdeluokka> i2=kohdeluokat.iterator(); 
    assertEquals("From: Kohdeluokat line: 84", testi21, i2.next()); 
    assertEquals("From: Kohdeluokat line: 85", testi11, i2.next()); 
    assertEquals("From: Kohdeluokat line: 86", testi22, i2.next()); 
    assertEquals("From: Kohdeluokat line: 87", testi12, i2.next()); 
    assertEquals("From: Kohdeluokat line: 88", testi23, i2.next()); 
    try {
    assertEquals("From: Kohdeluokat line: 89", testi12, i2.next()); 
    fail("Kohdeluokat: 89 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int nrot[] = { 2,1,2,1,2} ; 
    for ( Kohdeluokka koh:kohdeluokat ) {
    assertEquals("From: Kohdeluokat line: 95", nrot[n], koh.getKohdeNro()); n++; 
    }
    assertEquals("From: Kohdeluokat line: 98", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKohdeluokat113 */
  @Test
  public void testAnnaKohdeluokat113() {    // Kohdeluokat: 113
    Kohdeluokat kohdeluokat = new Kohdeluokat(); 
    Kohdeluokka testi21 = new Kohdeluokka(2); kohdeluokat.lisaa(testi21); 
    Kohdeluokka testi11 = new Kohdeluokka(1); kohdeluokat.lisaa(testi11); 
    Kohdeluokka testi22 = new Kohdeluokka(2); kohdeluokat.lisaa(testi22); 
    Kohdeluokka testi12 = new Kohdeluokka(1); kohdeluokat.lisaa(testi12); 
    Kohdeluokka testi23 = new Kohdeluokka(2); kohdeluokat.lisaa(testi23); 
    Kohdeluokka testi51 = new Kohdeluokka(5); kohdeluokat.lisaa(testi51); 
    List<Kohdeluokka> loytyneet; 
    loytyneet = kohdeluokat.annaKohdeluokat(3); 
    assertEquals("From: Kohdeluokat line: 126", 0, loytyneet.size()); 
    loytyneet = kohdeluokat.annaKohdeluokat(1); 
    assertEquals("From: Kohdeluokat line: 128", 2, loytyneet.size()); 
    assertEquals("From: Kohdeluokat line: 129", true, loytyneet.get(0) == testi11); 
    assertEquals("From: Kohdeluokat line: 130", true, loytyneet.get(1) == testi12); 
    loytyneet = kohdeluokat.annaKohdeluokat(5); 
    assertEquals("From: Kohdeluokat line: 132", 1, loytyneet.size()); 
    assertEquals("From: Kohdeluokat line: 133", true, loytyneet.get(0) == testi51); 
  } // Generated by ComTest END
}