package kohdeluettelo;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2015.07.29 23:51:33 // Generated by ComTest
 *
 */
public class KohdeTest {



  // Generated by ComTest BEGIN
  /** testAseta136 */
  @Test
  public void testAseta136() {    // Kohde: 136
    Kohde kohde = new Kohde(); 
    assertEquals("From: Kohde line: 138", null, kohde.aseta(1,"Merkurius")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi247 */
  @Test
  public void testRekisteroi247() {    // Kohde: 247
    Kohde merkurius = new Kohde(); 
    assertEquals("From: Kohde line: 249", 0, merkurius.getKohdeNro()); 
    merkurius.rekisteroi(); 
    Kohde venus = new Kohde(); 
    venus.rekisteroi(); 
    int n1 = merkurius.getKohdeNro(); 
    int n2 = venus.getKohdeNro(); 
    assertEquals("From: Kohde line: 255", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString337 */
  @Test
  public void testToString337() {    // Kohde: 337
    Kohde kohde = new Kohde(); 
    kohde.parse("   2  |  Venus   | "); 
    assertEquals("From: Kohde line: 340", true, kohde.toString().startsWith("2|Venus|"));  // on enemmäkin kuin 2 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse362 */
  @Test
  public void testParse362() {    // Kohde: 362
    Kohde Kohde = new Kohde(); 
    Kohde.parse("   1  |  Merkurius   | "); 
    assertEquals("From: Kohde line: 365", 1, Kohde.getKohdeNro()); 
    assertEquals("From: Kohde line: 366", true, Kohde.toString().startsWith("1|Merkurius|"));  // on enemmäkin kuin 2 kenttää, siksi loppu |
    Kohde.rekisteroi(); 
    int n = Kohde.getKohdeNro(); 
    Kohde.parse(""+(n+20));  // Otetaan merkkijonosta vain kohdenumero
    Kohde.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kohde line: 372", n+20+1, Kohde.getKohdeNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone386 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone386() throws CloneNotSupportedException {    // Kohde: 386
    Kohde kohde = new Kohde(); 
    kohde.parse("   4  |  Mars   | "); 
    Kohde kopio = kohde.clone(); 
    assertEquals("From: Kohde line: 391", kohde.toString(), kopio.toString()); 
    kohde.parse("   4  |  Mars Jupiter   | "); 
    assertEquals("From: Kohde line: 393", false, kopio.toString().equals(kohde.toString())); 
  } // Generated by ComTest END
}